### ISSUE TITLE
I saw a familiar project in github

### ISSUE THREAD

**Issue by xyfy** [gnsilence/HangfireHttpJob#3]
I saw a familiar project in github
[https://github.com/yuzd/Hangfire.HttpJob](url)

do you know it ?can you get a cooperation?

**Comment by gnsilence** [comment]
> I saw a familiar project in github
> https://github.com/yuzd/Hangfire.HttpJob
> do you know it ?can you get a cooperation?

A long time ago，I saw his code，At that time it was a simple function.
At that time, the author stopped maintenance.
Later, I expanded many functions on this basis.
Now you see that project, the author restarted the maintenance, there are many functions are borrowed from me here, or directly quoted.
I may continue to maintain my project because we may have different ideas and uses.
You can also continue to focus on that other project.
